Create DELETE API handler for Todo list (#41)
SE701Group2/daily-focus pull request #87
Opened 2021-03-20 13:51 UTC by LincRui

Issue:
#41 

Test Method:
Importing an Example.json to the firebase real-time database. Useing postman to send a delete request to the endpoint localhost:3000/todos. After the last process, double-check the database, the data has been deleted.

Risk:
N/A

2021-03-20 22:12 UTC, Pranavan10 approved these changes

2021-03-21 02:52 UTC, jonathan-thamrin requested changes
Small nitpick but don't forget to apply formatting with Prettier

2021-03-21 02:52 UTC, jonathan-thamrin commented on server/routes/tests/delete.todo.test.js
> +    0: {
There seems to be syntax errors with how this array is set up. Can be fixed with the following :)

```suggestion
    {
```

2021-03-21 02:52 UTC, jonathan-thamrin commented on server/routes/tests/delete.todo.test.js
> +    1: {
Refer to previous comment for reason.
```suggestion
    {
```

2021-03-21 02:52 UTC, jonathan-thamrin commented on server/routes/tests/delete.todo.test.js
> +    0: {
Refer to previous comment for reason.
```suggestion
    {
```

2021-03-21 02:58 UTC, LincRui commented on server/routes/tests/delete.todo.test.js
> +    0: {
Thanks, bro. Learned it.

2021-03-22 22:13 UTC, raymondhonsumchiu commented
Might need to apply recent changes in main via rebasing before you can merge this pull request

2021-03-24 06:27 UTC, raymondhonsumchiu approved these changes
Everything looks good now!

2021-03-24 06:29 UTC, jonathan-thamrin approved these changes

2021-03-24 06:33 UTC, merged