#14 create body component
SE701Group2/daily-focus pull request #88
Opened 2021-03-20 22:02 UTC by Chuppay

Issue:
#14

Solution:
Added screen for no widgets on the page
Added Material UI grid to house the future widgets
List of widgets obtained from the persisted state

Test Method:
Test if component renders without crashing
Snapshot test of component rendering properly

Risk:
Does not know any current widgets so it will render cards with the widget names
There are no widgets currently being updated in the persisted state

Reviewed By:

2021-03-20 22:20 UTC, Denijar requested changes
Looking good! Just found a lil console.log hehe

2021-03-20 22:20 UTC, Denijar commented on client/src/components/Body/index.js
> +    console.log(selectedWidgets);
👀

2021-03-20 23:10 UTC, kcho9906 commented on client/src/components/Body/index.js
> +                            <Paper>{value}</Paper>
Gonna have to swap this out later but will do for now

2021-03-20 23:10 UTC, kcho9906 approved these changes
Great work @Chuppay

2021-03-21 01:15 UTC, Denijar approved these changes
LGTM

2021-03-21 01:15 UTC, merged